/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package millane_proyecto2;

import java.util.concurrent.Semaphore;
import javax.swing.JTextField;

/**
 *
 * @author leste
 */
public class Interfaz extends javax.swing.JFrame {
    
    Semaphore mutex= new Semaphore(1);
    Empresa Nintendo= new Empresa();
    
    Empresa Capcom= new Empresa();
    Administrador admin= new Administrador(mutex,Nintendo,Capcom);
    Minijuego mini = new Minijuego();
    
    AI ERMG= new AI(mutex, 1, Nintendo, Capcom, mini);

    
    
    HilosGui gui= new HilosGui(getAreaTextoC1(),Nintendo,Capcom);
      
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        Nintendo.llenarBDD("Nintendo");
        Capcom.llenarBDD("Capcom");
//       
//         gui.start();
        admin.start();
    }

    public JTextField getAreaTextoC1() {
        return AreaTextoC1;
    }

    public void setAreaTextoC1(JTextField AreaTextoC1) {
        this.AreaTextoC1 = AreaTextoC1;
    }

    public JTextField getAreaTextoC2() {
        return AreaTextoC2;
    }

    public void setAreaTextoC2(JTextField AreaTextoC2) {
        this.AreaTextoC2 = AreaTextoC2;
    }

    public JTextField getAreaTextoC3() {
        return AreaTextoC3;
    }

    public void setAreaTextoC3(JTextField AreaTextoC3) {
        this.AreaTextoC3 = AreaTextoC3;
    }

    public JTextField getAreaTextoC4() {
        return AreaTextoC4;
    }

    public void setAreaTextoC4(JTextField AreaTextoC4) {
        this.AreaTextoC4 = AreaTextoC4;
    }

    public JTextField getAreaTextoZ1() {
        return AreaTextoZ1;
    }

    public void setAreaTextoZ1(JTextField AreaTextoZ1) {
        this.AreaTextoZ1 = AreaTextoZ1;
    }

    public JTextField getAreaTextoZ2() {
        return AreaTextoZ2;
    }

    public void setAreaTextoZ2(JTextField AreaTextoZ2) {
        this.AreaTextoZ2 = AreaTextoZ2;
    }

    public JTextField getAreaTextoZ3() {
        return AreaTextoZ3;
    }

    public void setAreaTextoZ3(JTextField AreaTextoZ3) {
        this.AreaTextoZ3 = AreaTextoZ3;
    }

    public JTextField getAreaTextoZ4() {
        return AreaTextoZ4;
    }

    public void setAreaTextoZ4(JTextField AreaTextoZ4) {
        this.AreaTextoZ4 = AreaTextoZ4;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nintendo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        AreaTextoZ1 = new javax.swing.JTextField();
        AreaTextoZ2 = new javax.swing.JTextField();
        AreaTextoZ3 = new javax.swing.JTextField();
        AreaTextoZ4 = new javax.swing.JTextField();
        capcom = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AreaTextoC1 = new javax.swing.JTextField();
        AreaTextoC4 = new javax.swing.JTextField();
        AreaTextoC3 = new javax.swing.JTextField();
        AreaTextoC2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nintendo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Cola 4");
        nintendo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel11.setText("Cola 3");
        nintendo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel10.setText("Cola 2");
        nintendo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel1.setText("Nintendo");
        nintendo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 20));

        jLabel3.setText("jLabel3");
        nintendo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel18.setText("Cola 1");
        nintendo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        nintendo.add(AreaTextoZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, -1));
        nintendo.add(AreaTextoZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, -1));
        nintendo.add(AreaTextoZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 130, -1));
        nintendo.add(AreaTextoZ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, -1));

        jPanel1.add(nintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 500));

        capcom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Cola 4");
        capcom.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jLabel14.setText("Cola 3");
        capcom.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jLabel15.setText("Cola 2");
        capcom.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel16.setText("Cola 1");
        capcom.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jLabel2.setText("Capcom");
        capcom.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel4.setText("jLabel4");
        capcom.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));
        capcom.add(AreaTextoC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, -1));
        capcom.add(AreaTextoC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, -1));
        capcom.add(AreaTextoC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 130, -1));
        capcom.add(AreaTextoC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, -1));

        jPanel1.add(capcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 310, 500));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel17.setText("Cola 1");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(admin.getPersonaje1().getNombre());
        System.out.println(admin.getPersonaje2().getNombre());
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaTextoC1;
    private javax.swing.JTextField AreaTextoC2;
    private javax.swing.JTextField AreaTextoC3;
    private javax.swing.JTextField AreaTextoC4;
    private javax.swing.JTextField AreaTextoZ1;
    private javax.swing.JTextField AreaTextoZ2;
    private javax.swing.JTextField AreaTextoZ3;
    private javax.swing.JTextField AreaTextoZ4;
    private javax.swing.JPanel capcom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel nintendo;
    // End of variables declaration//GEN-END:variables
}
